<?php
if ( ! defined( 'ABSPATH' ) ) {
    die( '-1' );
}

if (function_exists('vc_map')) {
    vc_map(array(
        'name'              => esc_html__('GT3 Sticky Side', 'oconnor'),
        'description'       => esc_html__("Display Sticky Side", 'oconnor'),
        'category'          => esc_html__('GT3 Modules', 'oconnor'),
        'base'              => 'gt3_sticky_side',
        'class'             => 'gt3_sticky_side',
        'icon'              => 'gt3_icon',
        // 'show_settings_on_create' => true,
        'show_settings_on_create' => false,
        'is_container'      => true,
        'as_parent'         => array('only' => 'vc_row'),
        'content_element'   => true,
        'js_view'           => 'VcColumnView',
        'params'            => array(
            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__( 'Sticky Side Height', 'oconnor' ),
                'param_name'        => 'sticky_height',
                'options'             => array(
                    esc_html__("Full Height", 'oconnor') => 'full',
                    esc_html__("Default", 'oconnor')     => 'default',
                ),
                'std'               => 'slide',
            ),
            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__('Image Option', 'oconnor'),
                'param_name'        => 'image_option',
                'options'             => array(
                    esc_html__("Cover", 'oconnor')     => 'cover',
                    esc_html__("Contain", 'oconnor')   => 'contain',
                    esc_html__("No repeat", 'oconnor') => 'no-repeat',
                ),
                'std'               => 'cover',
                'edit_field_class'  => 'vc_col-sm-6',
                'dependency'        => array(
                    'element'           => 'sticky_height',
                    'value'             => 'full',
                ),
            ),
            array(
                'type'              => 'dropdown',
                'heading'           => esc_html__('Image Position', 'oconnor'),
                'param_name'        => 'image_position',
                'value'             => array(
                    esc_html__("Top Left", 'oconnor')      => 'top left',
                    esc_html__("Top Center", 'oconnor')    => 'top center',
                    esc_html__("Top Right", 'oconnor')     => 'top right',
                    esc_html__("Center Left", 'oconnor')   => 'center left',
                    esc_html__("Center Center", 'oconnor') => 'center center',
                    esc_html__("Center Right", 'oconnor')  => 'center right',
                    esc_html__("Bottom Left", 'oconnor')   => 'bottom left',
                    esc_html__("Bottom Center", 'oconnor') => 'bottom center',
                    esc_html__("Bottom Right", 'oconnor')  => 'bottom right',
                ),
                'std'               => 'center center',
                'edit_field_class'  => 'vc_col-sm-6',
                'dependency'        => array(
                    'element'           => 'sticky_height',
                    'value'             => 'full',
                ),
            ),

            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Autoplay carousel', 'oconnor' ),
                'param_name'        => 'autoplay_carousel',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'std'               => 'yes',
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__( 'Slider speed', 'oconnor' ),
                'param_name'        => 'slider_speed',
                'value'             => '3000',
                'description'       => esc_html__( 'Enter autoplay time in milliseconds.', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'autoplay_carousel',
                    'value'             => array("yes"),
                ),
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Infinity Scroll', 'oconnor' ),
                'param_name'        => 'infinity_scroll',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'std'               => 'yes',
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Hide prev/next buttons', 'oconnor' ),
                'param_name'        => 'use_prev_next',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'std'               => 'no',
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Hide dots', 'oconnor' ),
                'param_name'        => 'use_pagination',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'std'               => 'no',
            ),
            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__( 'Animation', 'oconnor' ),
                'param_name'        => 'animation',
                'options'             => array(
                    esc_html__("Slide", 'oconnor') => 'slide',
                    esc_html__("Fade", 'oconnor')  => 'fade',
                ),
                'std'               => 'slide',
            ),


            /* Slides Styling */
            array(
                'type'              => 'param_group',
                'heading'           => esc_html__( 'Values', 'oconnor' ),
                'param_name'        => 'values',
                'description'       => esc_html__( 'Enter values for graph - value, title and color.', 'oconnor' ),
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'params'            => array(

                    array(
                        'type'              => 'attach_image',
                        'heading'           => esc_html__( 'Slider Image', 'oconnor' ),
                        'param_name'        => 'slider_image',
                        'value'             => '',
                        'admin_label'       => true,
                    ),
                    array(
                        'type'              => 'textfield',
                        'heading'           => esc_html__( 'Title', 'oconnor' ),
                        'param_name'        => 'slider_title',
                        'admin_label'       => true,
                    ),
                    array(
                        'type'              => 'textarea',
                        'heading'           => esc_html__( 'Text', 'oconnor' ),
                        'param_name'        => 'slider_text',
                        'admin_label'       => true,
                    ),
                    array(
                        'type'              => 'colorpicker',
                        'heading'           => esc_html__( 'Title color', 'oconnor' ),
                        'param_name'        => 'slider_title_color',
                        'description'       => esc_html__( 'Select title color.', 'oconnor' ),
                        'edit_field_class'  => 'vc_col-sm-6',
                        'std'               => '#ffffff',
                    ),
                    array(
                        'type'              => 'colorpicker',
                        'heading'           => esc_html__( 'Text color', 'oconnor' ),
                        'param_name'        => 'slider_text_color',
                        'description'       => esc_html__( 'Select text color.', 'oconnor' ),
                        'edit_field_class'  => 'vc_col-sm-6',
                        'std'               => '#ffffff',
                    ),
                    array(
                        'type'              => 'colorpicker',
                        'heading'           => esc_html__( 'Shadow color', 'oconnor' ),
                        'param_name'        => 'slider_shadow_color',
                        'description'       => esc_html__( 'Select shadow color.', 'oconnor' ),
                        'edit_field_class'  => 'vc_col-sm-12',
                        'std'               => 'rgba(0,0,0,0.7)',
                    ),
                ),
            ),

            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__('Title and Text Align', 'oconnor'),
                'param_name'        => 'content_align',
                'options'             => array(
                    esc_html__("Left", 'oconnor')   => 'left',
                    esc_html__("Right", 'oconnor')  => 'right',
                    esc_html__("Center", 'oconnor') => 'center',
                ),
                'std'               => 'center',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'colorpicker',
                'heading'           => esc_html__( 'Dots color', 'oconnor' ),
                'param_name'        => 'slider_dots_color',
                'description'       => esc_html__( 'Select dots color.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'std'               => '#ffffff',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__( 'Image size', 'oconnor' ),
                'param_name'        => 'img_size',
                'value'             => 'large',
                'description'       => esc_html__( 'Enter image size. Example: thumbnail, medium, large, full or other sizes defined by current theme. Alternatively enter image size in pixels: 200x100 (Width x Height). Leave empty to use "thumbnail" size.', 'oconnor' ),
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'sticky_height',
                    'value_not_equal_to'=> 'full',
                ),
            ),

            /* Title Styling */
            array(
                'type'              => 'backend_divider',
                'heading'           => esc_html__('Title Styling', 'oconnor'),
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Title Font Size', 'oconnor'),
                'param_name'        => 'title_font_size',
                'value'             => '60',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Title Line Height', 'oconnor'),
                'param_name'        => 'title_line_height',
                'value'             => '140',
                'description'       => esc_html__( 'Enter line height in %.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Set Responsive Font Size for Title', 'oconnor' ),
                'param_name'        => 'title_responsive_font',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'value'            => array(esc_html__('Yes', 'oconnor') => 'yes'),
                'std'              => 'no',
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for small Desktops', 'oconnor'),
                'param_name'        => 'title_font_size_sm_desktop',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'title_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for Tablets', 'oconnor'),
                'param_name'        => 'title_font_size_tablet',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'title_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for Mobile', 'oconnor'),
                'param_name'        => 'title_font_size_mobile',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'title_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Use theme default font family for Title?', 'oconnor' ),
                'param_name'        => 'title_use_theme_fonts',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'description'       => esc_html__( 'Use font family from the theme.', 'oconnor' ),
                'std'               => 'yes',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'google_fonts',
                'param_name'        => 'title_google_fonts',
                'value'             => '',
                'settings'          => array(
                    'fields'            => array(
                        'font_family_description' => esc_html__( 'Select font family.', 'oconnor' ),
                        'font_style_description'  => esc_html__( 'Select font styling.', 'oconnor' ),
                    ),
                ),
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'            => 'title_use_theme_fonts',
                    'value_not_equal_to' => 'yes',
                ),
            ),
            /* Title Styling end */


            /* Text Styling */
            array(
                'type'              => 'backend_divider',
                'heading'           => esc_html__('Text Styling', 'oconnor'),
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Text Font Size', 'oconnor'),
                'param_name'        => 'text_font_size',
                'value'             => '24',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Text Line Height', 'oconnor'),
                'param_name'        => 'text_line_height',
                'value'             => '140',
                'description'       => esc_html__( 'Enter line height in %.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Set Responsive Font Size for Text', 'oconnor' ),
                'param_name'        => 'text_responsive_font',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for small Desktops', 'oconnor'),
                'param_name'        => 'text_font_size_sm_desktop',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'text_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for Tablets', 'oconnor'),
                'param_name'        => 'text_font_size_tablet',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'text_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'textfield',
                'heading'           => esc_html__('Font Size for Mobile', 'oconnor'),
                'param_name'        => 'text_font_size_mobile',
                'description'       => esc_html__( 'Enter font-size in pixels.', 'oconnor' ),
                'edit_field_class'  => 'vc_col-sm-6',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'text_responsive_font',
                    "value"             => "yes",
                ),
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Use theme default font family for Text?', 'oconnor' ),
                'param_name'        => 'text_use_theme_fonts',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'description'       => esc_html__( 'Use font family from the theme.', 'oconnor' ),
                'std'               => 'yes',
                'group'             => esc_html__( 'Slides', 'oconnor' ),
            ),
            array(
                'type'              => 'google_fonts',
                'param_name'        => 'text_google_fonts',
                'value'             => '',
                'settings'          => array(
                    'fields'            => array(
                        'font_family_description' => esc_html__( 'Select font family.', 'oconnor' ),
                        'font_style_description'  => esc_html__( 'Select font styling.', 'oconnor' ),
                    ),
                ),
                'group'             => esc_html__( 'Slides', 'oconnor' ),
                'dependency'        => array(
                    'element'            => 'text_use_theme_fonts',
                    'value_not_equal_to' => 'yes',
                ),
            ),
            /* Text Styling end */


            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__( 'Select Gap between Sticky side and Content', 'oconnor' ),
                'param_name'        => 'gap',
                'options'             => array(
                    esc_html__( 'None', 'oconnor' )    => 'None',
                    esc_html__( '5px', 'oconnor' )     => '5',
                    esc_html__( '10px', 'oconnor' )    => '10',
                    esc_html__( '15px', 'oconnor' )    => '15',
                    esc_html__( '20px', 'oconnor' )    => '20',
                    esc_html__( '25px', 'oconnor' )    => '25',
                    esc_html__( '30px', 'oconnor' )    => '30',
                    esc_html__( '35px', 'oconnor' )    => '35',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => '',
                'std'               => 'left',
            ),
            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__( 'Carousel position (Sticky side position)', 'oconnor' ),
                'param_name'        => 'position',
                'options'             => array(
                    esc_html__( 'Left', 'oconnor' )  => 'left',
                    esc_html__( 'Right', 'oconnor' ) => 'right',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => '',
                'std'               => 'left',
            ),
            /* Carousel Responsive */
            array(
                'type'              => 'backend_divider',
                'heading'           => esc_html__('Carousel Responsive', 'oconnor'),
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
            ),
            array(
                'type'              => 'dropdown',
                'heading'           => esc_html__( 'Carousel width', 'oconnor' ),
                'param_name'        => 'carousel_width',
                'value'             => array(
                    esc_html__( '1 column - 1/12', 'oconnor' )    => '1/12',
                    esc_html__( '2 columns - 1/6', 'oconnor' )    => '1/6',
                    esc_html__( '3 columns - 1/4', 'oconnor' )    => '1/4',
                    esc_html__( '4 columns - 1/3', 'oconnor' )    => '1/3',
                    esc_html__( '5 columns - 5/12', 'oconnor' )   => '5/12',
                    esc_html__( '6 columns - 1/2', 'oconnor' )    => '1/2',
                    esc_html__( '7 columns - 7/12', 'oconnor' )   => '7/12',
                    esc_html__( '8 columns - 2/3', 'oconnor' )    => '2/3',
                    esc_html__( '9 columns - 3/4', 'oconnor' )    => '3/4',
                    esc_html__( '10 columns - 5/6', 'oconnor' )   => '5/6',
                    esc_html__( '11 columns - 11/12', 'oconnor' ) => '11/12',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => esc_html__( 'Select column width.', 'oconnor' ),
                'std'               => '1/2',
            ),
            array(
                'type'              => 'backend_divider',
                'heading'           => '',
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
            ),
            array(
                'type'              => 'dropdown',
                'heading'           => esc_html__( 'Carousel width on small Desktops', 'oconnor' ),
                'param_name'        => 'carousel_width_small',
                'value'             => array(
                    esc_html__( '1 column - 1/12', 'oconnor' )    => '1/12',
                    esc_html__( '2 columns - 1/6', 'oconnor' )    => '1/6',
                    esc_html__( '3 columns - 1/4', 'oconnor' )    => '1/4',
                    esc_html__( '4 columns - 1/3', 'oconnor' )    => '1/3',
                    esc_html__( '5 columns - 5/12', 'oconnor' )   => '5/12',
                    esc_html__( '6 columns - 1/2', 'oconnor' )    => '1/2',
                    esc_html__( '7 columns - 7/12', 'oconnor' )   => '7/12',
                    esc_html__( '8 columns - 2/3', 'oconnor' )    => '2/3',
                    esc_html__( '9 columns - 3/4', 'oconnor' )    => '3/4',
                    esc_html__( '10 columns - 5/6', 'oconnor' )   => '5/6',
                    esc_html__( '11 columns - 11/12', 'oconnor' ) => '11/12',
                    esc_html__( '12 columns - 1/1', 'oconnor' )   => '1/1',
                    esc_html__( 'None', 'oconnor' )               => 'none',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => esc_html__( 'Select column width.', 'oconnor' ),
                'std'               => '1/2',
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Full width for Second part (Content part)', 'oconnor' ),
                'param_name'        => 'carousel_width_small_content',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'description'       => esc_html__( 'The Sticky effect will be deactivated.', 'oconnor' ),
                'std'               => '',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
            ),
            array(
                'type'              => 'backend_divider',
                'heading'           => '',
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
            ),
            array(
                'type'              => 'dropdown',
                'heading'           => esc_html__( 'Carousel width on Tablet', 'oconnor' ),
                'param_name'        => 'carousel_width_tablet',
                'value'             => array(
                    esc_html__( '1 column - 1/12', 'oconnor' )    => '1/12',
                    esc_html__( '2 columns - 1/6', 'oconnor' )    => '1/6',
                    esc_html__( '3 columns - 1/4', 'oconnor' )    => '1/4',
                    esc_html__( '4 columns - 1/3', 'oconnor' )    => '1/3',
                    esc_html__( '5 columns - 5/12', 'oconnor' )   => '5/12',
                    esc_html__( '6 columns - 1/2', 'oconnor' )    => '1/2',
                    esc_html__( '7 columns - 7/12', 'oconnor' )   => '7/12',
                    esc_html__( '8 columns - 2/3', 'oconnor' )    => '2/3',
                    esc_html__( '9 columns - 3/4', 'oconnor' )    => '3/4',
                    esc_html__( '10 columns - 5/6', 'oconnor' )   => '5/6',
                    esc_html__( '11 columns - 11/12', 'oconnor' ) => '11/12',
                    esc_html__( '12 columns - 1/1', 'oconnor' )   => '1/1',
                    esc_html__( 'None', 'oconnor' )               => 'none',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => esc_html__( 'Select column width.', 'oconnor' ),
                'std'               => '5/12',
            ),
            array(
                'type'              => 'gt3_on_off',
                'heading'           => esc_html__( 'Full width for Second part (Content part)', 'oconnor' ),
                'param_name'        => 'carousel_width_tablet_content',
                'value'             => array( esc_html__( 'Yes', 'oconnor' ) => 'yes' ),
                'description'       => esc_html__( 'The Sticky effect will be deactivated.', 'oconnor' ),
                'std'               => '',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'dependency'        => array(
                    'element'           => 'carousel_width_small_content',
                    'value_not_equal_to'=> 'yes',
                ),
            ),
            array(
                'type'              => 'backend_divider',
                'heading'           => '',
                'param_name'        => 'backend_divider',
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
            ),
            array(
                'type'              => 'gt3_custom_select',
                'heading'           => esc_html__( 'Carousel width on Mobile', 'oconnor' ),
                'param_name'        => 'carousel_width_mobile',
                'options'             => array(
                    esc_html__( '12 columns - 1/1', 'oconnor' )   => '1/1',
                    esc_html__( 'None', 'oconnor' )               => 'none',
                ),
                'group'             => esc_html__( 'Responsive Options', 'oconnor' ),
                'description'       => esc_html__( 'Select column width.', 'oconnor' ),
                'std'               => '1/1',
            ),
            array(
                "type"              => "textfield",
                "heading"           => esc_html__("Extra Class", 'oconnor'),
                "param_name"        => "el_class",
                "description"       => esc_html__("If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 'oconnor')
            ),
            array(
                'type'              => 'css_editor',
                'param_name'        => 'css',
                'group'             => esc_html__( 'Design Option', 'oconnor' ),
            ),
        ),
        'default_content' => '[vc_row_inner][vc_column_inner][/vc_column_inner][/vc_row_inner]',
    ));

    if (class_exists('WPBakeryShortCodesContainer')) {
        class WPBakeryShortCode_Gt3_Sticky_Side extends WPBakeryShortCodesContainer { }
    }
}